version: "3.3"

services:
  laravel_webserver:
    image: fococomunicacao/php73-apache
    container_name: laravel_webserver
    ports:
      - "80:80"
    volumes:
      - ./api:/var/www/html:Z
    links:
      - laravel_database
  laravel_database:
    image: mysql:5.7
    container_name: laravel_database
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql:Z
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      TZ: America/Sao_Paulo
